version: "3.8"

services:
  daprfrontend:
    image: frontend-dapr-react:latest
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"

  daprfrontend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprfrontend",
        "-app-port",
        "8080",
        "-placement-host-address",
        "placement:6050",
        "--components-path",
        "./components",
        "--config",
        "/components/config.yaml",
      ]
    depends_on:
      - daprfrontend
    env_file:
      - .env
    volumes:
      - "./components/:/components"
    network_mode: "service:daprfrontend"

  daprbackend:
    image: backend-dapr-flask:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"

  daprbackend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprbackend",
        "-app-port",
        "8000",
        "-placement-host-address",
        "placement:6050",
        "--components-path",
        "./components",
        "--config",
        "/components/config.yaml",
      ]
    env_file:
      - .env
    volumes:
      - "./components/:/components"
    depends_on:
      - daprbackend
    network_mode: "service:daprbackend"

  zipkin-dapr:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    command: ["java", "-jar", "zipkin.jar"]
