apiVersion: v1
kind: Pod
metadata:
  name: frontend-react-web
  labels:
    app: frontend-react
spec:
  containers:
    - name: frontend-react-container
      image: frontend-dapr-react:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080