kind: Service
apiVersion: v1
metadata:
  name: daprbackend
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprbackend
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprbackend"
        dapr.io/app-port: "8000"
    spec:
      containers:
      - name: flask
        image: backend-dapr-flask:latest
        ports:
        - containerPort: 8000
        # Set this to pull locally instead of from Dockerhub
        imagePullPolicy: IfNotPresent
        env: 
        - name: POSTGRES_USERNAME
          value: ""
        - name: POSTGRES_HOST
          value: ""
        - name: POSTGRES_PORT
          value: ""
        - name: POSTGRES_DATABASE
          value: ""
        - name: POSTGRES_PASSWORD
          value: ""
