apiVersion: v1
kind: Pod
metadata:
  name: dapr-distributed-application
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend-dapr-react"
        dapr.io/app-port: "8080"
  containers:
    - name: frontend-dapr-react
      image: frontend-dapr-react:latest
      # Set this to pull locally instead of from Dockerhub
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
    - name: backend-dapr-flask
      image: backend-dapr-flask:latest
      # Set this to pull locally instead of from Dockerhub
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      env: 
      - name: POSTGRES_USERNAME
        value: ""
      - name: POSTGRES_HOST
        value: ""
      - name: POSTGRES_PORT
        value: ""
      - name: POSTGRES_DATABASE
        value: ""
      - name: POSTGRES_PASSWORD
        value: ""
